.facility football,1

.severity severe
    ABSENT     "Other player has not entered game within timeout period"
    BADRECORD  "Bad record left by other player - please reenter game"
    BADUSER    "Username does not exist in the rights database"
    GHOSTED    "Other player seems to have ghosted"
    LONELY     "Football should be played with someone other than yourself"
    NOTSPAWN   "Football must be run in a spawned process"
    PLAYING    "Other player is currently engaged in another game"
.end
