gal.exe : gal_trader4.obj, display.obj, pname.obj
	link gal_trader4,display,pname/exe=gal.exe

gal_trader4.obj : gal_trader4.bas, gal-trader.h
	basic gal_trader4/variant=0

display.obj : display.bas, display.e
	basic display

pname.obj : pname.bas
	basic pname
