[H[J(B[0m
[1;1H#6[2;1H#3      Y E S   T H A T   W A S   A[3;1H#4      Y E S   T H A T   W A S   A[4;1H#6[5;1H#6[5;12HP O L I C E M A N
[6;1H#6[7;1H#6  [7m                                [8;1H#6[8;11H [0m  (0xx  xx  xx  [7m [9;1H#6[9;10H  [0m  xx  xx  xx  [7m 
[9;27H [10;1H#6[10;11H [0m  xx  xx  xx  [7m [11;1H#6[11;10H  [0m  xx  xx  xx  [7m  [12;1H#6[12;11H [0m  xx  xx  xx  [7m 
[13;1H#6[13;10H  [0m  xx  xx  xx  [7m  [14;1H#6[14;11H [0m  xx  xx  xx  [7m [15;1H#6[15;10H  [0m  xx  xx  xx  [7m  
[16;1H#6[16;11H      (B/  \      [17;1H#6[17;16H[0m/    \[18;1H#6[18;15H(0lqqqqqqk[19;1H#6[19;15Hx HOME x[20;1H#6[20;15Hx SWEETx
[21;1H#6[21;15Hx JAIL x[22;1H#6[22;15Hmqqqqqqj[23;1H#6[1;1H
(B*
